### ISSUE TITLE
task mode

### ISSUE THREAD

**Issue by jtauber** [deep-reader/DeepReader#52]
I can imagine using DeepReader for specific tasks, either student assessment or student/expert crowdsourcing. e.g. find all the finite verbs in this passage; or disambiguate the morphology of all the words in red.

I imagine the way this would work is that you'd be in task mode which would limit some of the things you can do until you leave the task. During the task, a widget would explain the task at hand, provide stats, etc.

**Comment by balain** [comment]
So, crazy idea(?). What if this task mode as a to-do list. E.g. create a component for widget development plan and manage/update it via the task mode to track progress/completed items. It would require an active host serving the management instance of DeepReader and provide a sandbox to test out various features - e.g. due dates, etc. But it would conflict with and/or potentially be confusing when using GitHub's issues list...

**Comment by jtauber** [comment]
@balain I like your idea but I think it's orthogonal to what I'm suggesting. I'm specifically referring to a mode of interacting with the text that assesses comprehension of that text. But I think your idea is great and think you should create a new issue for it. But it occurs to me: for your idea, how about we just build a widget that interacts with the GitHub API? Avoids the conflict with GitHub and gives us an out-of-the-box microservice to use already.

**Comment by jtauber** [comment]
Actually now that I think more about it, you could use GitHub integration not just for tasks that are orthogonal to the text (like your example of widget development plans) but actually for some crowdsourcing projects (although perhaps not student assessment). For example, imagine you had a repository where issues were labeled with CTS URNs or OSIS IDs. The GitHub widget could retrieve the relevant issue(s) for the passage being interacted with and let the reader view those issues and comment on them right from within the widget.

I stress this is different from the original intention of this issue which was more a quizzing mode.

I think what I'll do is close this issue and create (at least) two new ones to reflect my original intentions clearer plus the new ideas you've generated and inspired.
