### ISSUE TITLE
more styling cleanup

### ISSUE THREAD

**Issue by jtauber** [deep-reader/DeepReader#66]
I've got PR #65 with a lot of reorganization but there are a couple more things I didn't do so we can have more discussion.

1. I think we should have a separate file for theming variables (including the stuff from #51 but don't call it `common.scss` — maybe `theme.scss` would be better). It should JUST be variables but cover font and colour choices.

2. I think `common.scss` should still exist but be for small reusable things like the definition of `.click` or `li.hanging`

3. the widget styling could move to the Widget component (not 100% sure)

4. what's left in `App.vue` should mostly be skeleton stuff. Not sure if it could be further divided but I think we might want to move it all into `.scss` files anyway and keep `App.vue` lean.

**Comment by brosner** [comment]
I agree with this approach. In my opinion not much discussion needed. 😄

**Comment by jtauber** [comment]
I'm not 100% sure about 3, though. Are you a +1 on that or just +0 :-)

Need to work out whether 4 involves just one file (and if so what it should be called) or multiple files.

**Comment by jtauber** [comment]
For 4, if it looks like what's left is more than just skeleton code I might split it into `skeleton.scss` and `app.scss` or something otherwise just use `skeleton.scss`
