### ISSUE TITLE
consider putting widget components in different place than non-widget components

### ISSUE THREAD

**Issue by jtauber** [deep-reader/DeepReader#69]

**Comment by brosner** [comment]
I think this is a good idea.

Since we have treated Vue components and widgets as completely interchangable there will be eventually be a distinction (even if they are still just Vue components). It will also make it clear to understand what is a widget versus something in the "core" that should expose and use generic interfaces.

**Comment by jtauber** [comment]
So first question is whether `widgets` is parallel to `components` or a child thereof.

I slightly prefer them being parallel (to keep widgets top-level) but that's also slightly misleading as widgets are still components.

**Comment by brosner** [comment]
I understand the thinking of trying to be pure about file structure, but I think we should go with that we like best and I am in favor using a top-level widgets directory.

**Comment by jtauber** [comment]
So what we'll do is create `widgets/` directory parallel to `components/` and move any widgets there. The `components/` directory then really just becomes non-widget components.

**Comment by jtauber** [comment]
Actually, I guess there's one other question: do the groupings like `morphgnt` go above or below?

i.e. is it

```
morphgnt/
    widgets/
    components/
```

or

```
widgets/
    morphgnt/
components
    morphgnt/
```

?

**Comment by brosner** [comment]
Good question. I think we end up with both. If it is a widget clearly specific to one text service it should live in the former, but if it is a widget that can easily be used for both then the latter (just under `widgets`).

The latter approach only would result in mixing the directories and global components together (meh) or the creation of a global directory (also meh).

That's my thinking.

**Comment by jtauber** [comment]
So does that mean:

```
widgets/
    ...global widgets...
components/
    ...global non-widget component...
morphgnt/
    widgets/
        ...morphgnt-specific widgets...
    components/
        ...morphgnt-specific non-widget components...
cts/
    widgets/
        ...cts-specific widgets...
    components/
        ...cts-specific non-widget components...
```

?

**Comment by brosner** [comment]
Yep. The net difference based on current tree ends up being adding widgets directory to each level and moving the widget components over. I hope over time we find the common interfaces and end up having using more global components / widgets every where.
