### ISSUE TITLE
Convert hrefs in reader-nav to router-links

### ISSUE THREAD

**Issue by balain** [deep-reader/DeepReader#73]
Pull request #72 = Suggest changing reader-nav hrefs to router-links

**Comment by jtauber** [comment]
Thanks very much for this! I'd add an AUTHORS file so I can give all contributors credit. What name should I use?

**Comment by balain** [comment]
John D. Lewis

I also have an update to create a home page. Will submit the pull request
shortly.

Thanks. Very excited about this tool.

**Comment by jtauber** [comment]
Oh, hi John!

I look forward to collaborating with you more on this.

**Comment by balain** [comment]
Looks like I already put my Homepage component in -- it was added to the router-link pull request. Thanks for merging it in.
